class BaseException(Exception):
    pass


class NotFoundError(BaseException):
    pass
